const { PrismaClient } = require('@prisma/client');
const fs = require('fs');
const path = require('path');

const prisma = new PrismaClient();

// Load data from JSON files (generated by migrate-data.js script)
const dataDir = path.join(__dirname, 'data');

function loadJsonFile(filename) {
    const filePath = path.join(dataDir, filename);
    if (fs.existsSync(filePath)) {
        return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    }
    return null;
}

async function main() {
    console.log('🌱 Starting database seed...');

    // Try to load migrated data
    let categories = loadJsonFile('categories.json');
    let allData = loadJsonFile('all-data.json');

    // If no migrated data, use default sample data
    if (!categories) {
        console.log('⚠️ No migrated data found. Using sample data.');
        console.log('   Run "node scripts/migrate-data.js" from project root to migrate existing data.\n');
        
        categories = [
            {
                name: 'basic',
                displayName: 'Basic Web3 Concepts',
                description: 'Master the foundational concepts of blockchain and Web3 technology',
                icon: '📗',
                order: 1
            },
            {
                name: 'intermediate',
                displayName: 'Intermediate Concepts',
                description: 'Deep dive into smart contracts, DeFi, and Web3 development',
                icon: '📘',
                order: 2
            },
            {
                name: 'advanced',
                displayName: 'Advanced Topics',
                description: 'Expert-level questions on Layer 2, MEV, security, and more',
                icon: '📕',
                order: 3
            },
            {
                name: 'projects',
                displayName: 'Portfolio Projects',
                description: 'Build real-world Web3 applications to showcase your skills',
                icon: '🚀',
                order: 4
            },
            {
                name: 'rust',
                displayName: 'Rust for Web3',
                description: 'Complete Rust tutorial for blockchain development',
                icon: '🦀',
                order: 5
            }
        ];

        allData = {
            questions: {
                basic: [
                    {
                        title: "What is a blockchain?",
                        tags: ["fundamentals", "basic"],
                        answer: "<p>A blockchain is a distributed, immutable, and transparent digital ledger.</p>",
                        order: 0
                    }
                ],
                intermediate: [],
                advanced: [],
                projects: [],
                rust: []
            }
        };
    }

    // Clear existing data
    console.log('🗑️ Clearing existing data...');
    await prisma.completion.deleteMany();
    await prisma.bookmark.deleteMany();
    await prisma.question.deleteMany();
    await prisma.tag.deleteMany();
    await prisma.category.deleteMany();

    console.log('📦 Creating categories...');
    
    // Create categories
    for (const cat of categories) {
        await prisma.category.create({
            data: cat
        });
    }

    console.log('🏷️ Creating tags and questions...');

    // Create questions for each category
    for (const [categoryName, questions] of Object.entries(allData.questions)) {
        if (!questions || questions.length === 0) continue;

        const category = await prisma.category.findUnique({
            where: { name: categoryName }
        });

        if (!category) {
            console.log(`  ⚠️ Category not found: ${categoryName}`);
            continue;
        }

        console.log(`  📁 ${categoryName}: ${questions.length} questions`);

        for (let i = 0; i < questions.length; i++) {
            const q = questions[i];
            
            // Create or connect tags
            const tagConnections = [];
            const tags = q.tags || [];
            
            for (const tagName of tags) {
                // Clean tag name (remove difficulty- prefix for storage)
                const cleanTagName = tagName.replace('difficulty-', '');
                
                const tag = await prisma.tag.upsert({
                    where: { name: cleanTagName },
                    update: {},
                    create: { name: cleanTagName }
                });
                tagConnections.push({ id: tag.id });
            }

            await prisma.question.create({
                data: {
                    title: q.title,
                    answer: q.answer || '',
                    order: q.order ?? i,
                    categoryId: category.id,
                    tags: {
                        connect: tagConnections
                    }
                }
            });
        }
    }

    const questionCount = await prisma.question.count();
    const categoryCount = await prisma.category.count();
    const tagCount = await prisma.tag.count();

    console.log(`\n✅ Seed completed!`);
    console.log(`   📁 Categories: ${categoryCount}`);
    console.log(`   ❓ Questions: ${questionCount}`);
    console.log(`   🏷️ Tags: ${tagCount}`);
}

main()
    .catch((e) => {
        console.error('❌ Seed failed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
